# Generated by Django 4.2.4 on 2023-08-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profilestatus",
            options={"verbose_name_plural": "statuses"},
        ),
    ]
